code-for-chapel-hill/NC-COVID-Support

- dashboard.Rmd
Adding some base layer options using the MapTiler API. Can add more options if necessary
> adding some base layer options

- app/app.R
- dashboard.Rmd
Added a basic mock-up of what this would look like as a single file shiny app in a separate folder
> shiny app skeleton addition

- dashboard.Rmd
As I am a complete "R" newbie, these might not have been done in the "right" way, so feel free to comment / suggest the right way :)
I have added some CSS to override the default styles as the design was broken on mobile, normally if using Bootstrap I would write CSS as SCSS and compile it, but it seems this framework automatically includes the generic Bootstrap CSS, so hopefully for now this is ok :)
- Added some inline CSS to improve the title on mobile.
- Removed the "Map" and "List" titles as I don't think they are needed, it's obvious it's a map and list :)
- Added containers around the map and list which helps with the responsive design ( the map seems to screw up otherwise )
TODO: The list breaks the responsive design on mobile, and it would be nice to reformat it to make it look …
> Small changes for the responsive design.

- dashboard.Rmd
I've added the name as a clickable link to their website ( this should be an optional link if we have the data, currently if we don't have the data, it will be a broken link )
I have then added the address and the first notes ( Details ).
> Adding more detail to the markers

- dashboard.Rmd
Creating first reactive context for resource input to update map
> creating first reactive context

- .github/ISSUE_TEMPLATE/data-needs--issues.md
- dashboard.Rmd
Just adding the phone number, nothing revolutionary :)
> Adding the phone number to the data marker.

- dashboard.Rmd
> map and table tabsetting fix

- covid-19-support/src/App.vue
- covid-19-support/src/components/Highlights.vue
- covid-19-support/src/components/ValueBox.vue
This should add the sliding side nav and fix the size of the map on mobile, hopefully :)
> Sliding side navigation

- covid-19-support/.eslintrc.js
- covid-19-support/.prettierrc
- covid-19-support/public/index.html
- covid-19-support/src/App.vue
- covid-19-support/src/components/Header.vue
- covid-19-support/src/components/Highlights.vue
- covid-19-support/src/components/ResourceMap.vue
- covid-19-support/src/components/ResultsList.vue
- covid-19-support/src/components/SearchFilter.vue
- covid-19-support/src/constants.js
- covid-19-support/src/i18n.js
- covid-19-support/vue.config.js
It's still a work in progress, hopefully this will be useful for people to see it is starting to take shape.
This relates to ticket #34
> Adding an initial result list to the left hand slide out section

- covid-19-support/src/components/ValueBox.vue
This should finally fix issue #13
> Fixing the text placement.

- covid-19-support/src/App.vue
- covid-19-support/src/components/Highlights.vue
- covid-19-support/src/components/SearchFilter.vue
- covid-19-support/src/locales/en.json
> Adding support for Family Meals.

- covid-19-support/src/components/Header.vue
- covid-19-support/src/components/SearchFilter.vue
- covid-19-support/src/locales/en.json
> Adding an info panel to the left search bar to highlight Orange County and contributing.

- .github/workflows/ci.yml
- covid-19-support/jest.config.js
- covid-19-support/package-lock.json
- covid-19-support/package.json
- covid-19-support/src/components/Highlights.vue
- covid-19-support/src/components/ValueBox.vue
- covid-19-support/tests/unit/ValueBox.spec.js
Assuming this works, it should close issue #157
> Adding the VueJS unit testing framework and two initial tests.

- .github/workflows/ci.yml
- covid-19-support/.eslintrc.js
- covid-19-support/src/components/ValueBox.vue
There was an issue with the Intelisense working in the Unit tests, this fixes that issue. ( badly named Branch... )
> Just fixing an issue with Intelisense in VS Code

- covid-19-support/src/App.vue
- covid-19-support/src/components/ValueBox.vue
- covid-19-support/tests/unit/ValueBox.spec.js
previously it was showing all businesses that were NOT zero.
Added a couple more simple unit tests
> Changing logic so only businesses with a status of 1 are shown.

- covid-19-support/src/App.vue
- covid-19-support/src/components/BusinessDetails.vue
- covid-19-support/src/components/Highlights.vue
Thanks @KM-Hanson for spotting these, hopefully this fixes them all except your suggestion about the zoom levels which was not really a "bug" with this change, it's another feature we have not yet implemented :)
> Fixing the issues found by Kate, thanks :)

- covid-19-support/src/App.vue
- covid-19-support/src/components/ResourceMap.vue
- covid-19-support/src/themes/AmericanDemoTheme/theme.config.js
- covid-19-support/src/themes/AmericanDemoTheme/theme.content.js
- covid-19-support/src/themes/NCCovidSupport/theme.config.js
Moving the initial Lat / Lng centroid to the config files.
This should close the issue #191
> Fixing issue #191

- covid-19-support/src/App.vue
- covid-19-support/src/components/BusinessDetails.vue
- covid-19-support/src/locales/BabelEdit.babel
- covid-19-support/src/locales/ar.json
- covid-19-support/src/locales/en.json
- covid-19-support/src/locales/es.json
- covid-19-support/src/locales/fr.json
- covid-19-support/src/locales/ja.json
- covid-19-support/src/locales/ko.json
- covid-19-support/src/locales/ms.json
- covid-19-support/src/locales/zh.json
Also not display the date at all if it's invalid.
Closes: #184
> Parsing the last updated dates and displaying them in the same format

- covid-19-support/src/components/Header.vue
- covid-19-support/src/components/ResourceMap.vue
- covid-19-support/src/components/ResultsList.vue
- covid-19-support/src/scss/Main.scss
- covid-19-support/src/themes/CodeForAmericaDemoTheme/SCSS/custom.scss
- covid-19-support/src/themes/NCCovidSupport/SCSS/custom.scss
Adding theme colors to the drop down menus.
Sorting out some small alignment and spacing issues.
> Lots of small tweaks for the navigation.

- covid-19-support/src/components/OpeningHours.vue
- covid-19-support/src/components/ResourceMap.vue
- covid-19-support/src/themes/CodeForAmericaDemoTheme/SCSS/custom.scss
- covid-19-support/src/themes/NCCovidSupport/SCSS/custom.scss
This should close #211. In addition to making those changes and making the map key UI customizable, I made the color of the word "closed" in Business Details a lighter red in dark mode.
> Improving Map Key UI and making customizable, changing closed color

- covid-19-support/src/components/ResourceMap.vue
Making changes to size, position, and border radius of the user location button on small devices. Before and after are below:
> Fixing location icon on small devices

- covid-19-support/src/components/BusinessDetails.vue
- covid-19-support/src/components/IconListItem.vue
- covid-19-support/src/locales/en.json
- covid-19-support/src/themes/NCCovidSupport/SCSS/custom.scss
Joint effort with @readingdancer to add the get directions functionality across platforms in a way that's not overwhelming for the user! This should close #243. Chris still needs to add translations for the "Get directions" text.
> Get directions functionality with google maps, apple maps, and waze

- covid-19-support/package-lock.json
- covid-19-support/src/components/ResourceMap.vue
issue #247 - hide zoom controls for mobile
- removed the zoom controls on mobile devices & also moved the user location button down to the corner of the screen
issue #248 - improve usability of user location icon
- created new design 1 and 2 and touched up their displays on mobile devices
> issue #247 & #248

- covid-19-support/.eslintrc.js
- covid-19-support/src/App.vue
- covid-19-support/src/components/BusinessDetails.vue
- covid-19-support/src/components/Highlights.vue
- covid-19-support/src/components/ResourceMap.vue
- covid-19-support/src/components/ResultsList.vue
- covid-19-support/src/components/Sidebar.vue
Feel free to close if you feel this is too opinionated. This was something I noticed while working on my last PR but I felt it should probably be separate. The main goal is to just have this syntax be consistent.
> Update object method syntax

- covid-19-support/src/App.vue
- covid-19-support/src/components/Highlights.vue
- covid-19-support/src/components/MobileSearchFilters.vue
- covid-19-support/src/components/ResultsList.vue
- covid-19-support/src/components/SearchFilters.vue
- covid-19-support/src/components/Sidebar.vue
- covid-19-support/src/components/ValueBox.vue
- covid-19-support/src/scss/main.scss
- covid-19-support/src/scss/variables.scss
> Issue 260: Remove when do you need it drop down

- covid-19-support/src/components/SearchFilters.vue
// { value: 'restaurant', text: this.$tc('category.restaurant', 2) },
// { value: 'food_bev', text: this.$tc('category.food_bev', 2) },
// { value: 'farm', text: this.$tc('category.farm', 2) },
> Removing the following:
